### ISSUE TITLE
Actually open-source?

### ISSUE THREAD

**Issue by animepony** [OpenIB/OpenIB#78]
It seems that features that are added to 8chan which are not reflected in this repo. Is this intended? If so, updating README.md is probably appropriate to reflect this.

**Comment by Cipherwraith** [comment]
We dont publish our anti-spam efforts. Doing so would be akin to keeping your poker cards face up and trying to bluff that you have a royal flush when you really just have a pair of Jacks.

**Comment by animepony** [comment]
Thanks for the reply.

What anti-spam efforts are you referring to? How are they employed?
If, for example, you have a list of regex filters, you don't need to publish those regex filters; simply allow a list of regex filters to be configurable by the end user.

If you're referring to the recent addition of the global-captcha protection mechanism, why not release the associated code, but don't release the (actual) configuration variables?

Also regarding non-included code: Based on my reading of config.php and posts on /tech/ that I have read, it would seem the Alacrity daemon related code is not included in this repo. Is that code located on a private branch? Do you intend to release the alacrity-related code in the future?

In any case, I doubt that releasing the anti-spam code will open 8chan up to attacks. With enough time and testing, the way that the anti-spam code is implemented will quickly become apparent to an attacker.
