### ISSUE TITLE
Rewrite it in Rust

### ISSUE THREAD

**Issue by InaneBob** [OpenIB/OpenIB#91]
So, like, I heard about "memory safety" and stuff, and thought, "who wouldn't want that"?
so rewrite everything in rust, now. chop chop
I would gladly help in this endeavour!

**Comment by animepony** [comment]
Please close this, is spam

**Comment by InaneBob** [comment]
memory and thread safety at unrivaled speed is not a meme.

**Comment by InaneBob** [comment]
fine then. i will start writing my own imageboard in rust then.
